services:
  - type: web
    name: house-price-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    workingDir: server
    autoDeploy: true
